In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 비침수 데이터 DIST=0

In [5]:
Unf_Final_V1 = pd.read_excel('Reflux_data/Final_V1/Unf_Final_V1.xlsx',index_col=False)
Unf_Final_V1.head()

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_L,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5

In [7]:
Unf_Final_V1['DIST']=0
Unf_Final_V1.to_excel("Reflux_data/Final_V1/Unf_Final_V1_01.xlsx")

In [9]:
Unf_Final_V1.head()

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH,DIST
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1,0
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2,0
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3,0
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4,0
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5,0

## 강수량이 있으면 DIST값이 1인 조건

In [10]:
F_Final_V1 = pd.read_excel('Reflux_data/Final_V1/F_Final_V1.xlsx',index_col=False)
F_Final_V1.head()

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_L,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5

In [11]:
# 조건에 따른 열값 바꾸기
# - 시간당 강수량이 0이상이면 DIST 값이 1

F_Final_V1.loc[(F_Final_V1['HOUR_RAINFALL'] > 0),'DIST'] = 1

In [13]:
# 조건에 따른 열값 바꾸기
# - 시간당 강수량이 0이면 DIST 값이 0

F_Final_V1.loc[(F_Final_V1['HOUR_RAINFALL'] == 0),'DIST'] = 0

In [14]:
F_Final_V1

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH,DIST
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1,0.0
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2,0.0
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3,1.0
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4,1.0
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,20,0.0
3956,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,21,0.0
3957,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,22,0.0
3958,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,23,0.0
3959,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,24,0.0

In [15]:
F_Final_V1.to_excel("Reflux_data/Final_V1/F_Final_V1_01.xlsx")

## 강우량 평균을 기준으로 다른 조건

In [16]:
F_Final_V1 = pd.read_excel('Reflux_data/Final_V1/F_Final_V1.xlsx',index_col=False)
F_Final_V1.head()

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_L,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,0.0,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5

In [17]:
# 조건에 따른 열값 바꾸기
# - 시간당 강수량의 평균을 구하고 그것을 기준으로 DIST값 지정


F_Final_V1[F_Final_V1['HOUR_RAINFALL']>0].mean() # 1.031633e+01

ADM_CD            2.641125e+09
SEQ               8.042377e+04
F_BEGIN_DE        2.014131e+07
F_END_DE          2.014131e+07
F_BEGIN_TM        1.511474e+03
F_END_TM          2.650839e+03
FLUD_TIME         1.082041e+01
FLUD_DPWT         5.812898e-01
SLOPE_L           2.807483e+00
SLOPE_H           7.692063e+00
SLOPE_AVG         5.249773e+00
HIGH              1.154917e+01
PUMP_RATIO        1.788663e-07
IMP_SUR_RATIO     3.730158e+01
MANHOLES_RATIO    1.348634e-02
HOUR_RAINFALL     1.031633e+01
PRECI_YYMMDDHH    2.014131e+07
PRECI_HH          1.111565e+01
dtype: float64

In [18]:
# 조건에 따른 열값 바꾸기
# - 시간당 강수량이 10초과이면 DIST 값이 1

F_Final_V1.loc[(F_Final_V1['HOUR_RAINFALL'] >= 10),'DIST'] = 1

In [19]:
# 조건에 따른 열값 바꾸기
# - 시간당 강수량이 10이하이면 DIST 값이 0

F_Final_V1.loc[(F_Final_V1['HOUR_RAINFALL'] < 10),'DIST'] = 0

In [20]:
F_Final_V1

,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,FLUD_TIME,...,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH,DIST
0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1,0.0
1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2,0.0
2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3,0.0
3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4,0.0
4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,13,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,20,0.0
3956,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,21,0.0
3957,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,22,0.0
3958,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,23,0.0
3959,2635010600,해운대구,중동,30587,중동지구,20090716,20090716,700,1100,4,...,7,4.5,4.65,2.102446e-07,27.63,0.016808,0.0,20090716,24,0.0

In [21]:
F_Final_V1.to_excel("Reflux_data/Final_V1/F_Final_V1_02.xlsx")

## F_Final_V1 불러오기

In [23]:
F_Final_V1 = pd.read_excel('Reflux_data/Final_V1/F_Final_V1_01.xlsx',index_col=False)
F_Final_V1.head()

,Unnamed: 0,ADM_CD,ZONE,Dong,SEQ,DISTRICT,F_BEGIN_DE,F_END_DE,F_BEGIN_TM,F_END_TM,...,SLOPE_H,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,HOUR_RAINFALL,PRECI_YYMMDDHH,PRECI_HH,DIST
0,0,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,1,0
1,1,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.0,20190719,2,0
2,2,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,0.1,20190719,3,1
3,3,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,4.1,20190719,4,1
4,4,2644010200,강서구,대저2동,102001,강동1지구,20190719,20190720,2300,1200,...,2,1.0,1.57,1.189961e-07,24.36,0.006944,6.1,20190719,5,1

In [24]:
F_Final_V1[F_Final_V1['DIST']==1].count() # 2205개

Unnamed: 0        2205
ADM_CD            2205
ZONE              2205
Dong              2205
SEQ               2205
DISTRICT          2205
F_BEGIN_DE        2205
F_END_DE          2205
F_BEGIN_TM        2205
F_END_TM          2205
FLUD_TIME         2205
FLUD_DPWT         2205
SLOPE_L           2205
SLOPE_H           2205
SLOPE_AVG         2205
HIGH              2205
PUMP_RATIO        2205
IMP_SUR_RATIO     2205
MANHOLES_RATIO    2205
HOUR_RAINFALL     2205
PRECI_YYMMDDHH    2205
PRECI_HH          2205
DIST              2205
dtype: int64